CREATE SEQUENCE region_seq;

CREATE TABLE IF NOT EXISTS region
(
    id   BIGINT CHECK (id > 0) NOT NULL DEFAULT NEXTVAL ('region_seq'),
    region VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT id_UNIQUE UNIQUE (id)
)
;