CREATE TABLE IF NOT EXISTS `schedule`
(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    `datetime` DATETIME NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE`(`id` ASC)
)
    ENGINE = InnoDB;